project:
  type: website
  output-dir: docs

website:
  title: "Jacob Weverka"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: CV
        href: CV.pdf

format:
  html:
    theme: slate
    css: styles.css
about:
  template: trestles
  image-shape: rounded
image: IMG_6917.JPG



