project:
  type: website
  output-dir: docs

website:
  title: "Jacob Weverka"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - text: CV
        href: CV/CV.pdf

format:
  html:
    theme: slate
    css: styles.css




