project:
  type: website
  output-dir: docs

website:
  title: "Jacob Weverka"
  navbar:
    title: Jacob Weverka
    left:
      - href: index.qmd
        text: Home
      - text: CV
        href: CV/CV.pdf
      - text: Research
        href: research.qmd

format:
  html:
    theme: slate
    css: styles.css




